In [24]:
%pip install catboost scikit-learn pandas

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: catboost in c:\users\49761366\appdata\roaming\python\python313\site-packages (1.2.10)
Requirement already satisfied: scikit-learn in c:\users\49761366\appdata\roaming\python\python313\site-packages (1.9.1)
Requirement already satisfied: pandas in c:\users\49761366\appdata\roaming\python\python313\site-packages (3.0.6)
Requirement already satisfied: graphviz in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (3.11.2)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (2.5.4)
Requirement already satisfied: scipy in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (1.18.1)
Requirement already satisfied: plotly in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (7.1.0)
Requirement already satisfied: six in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (1.17.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\49761366\appdata\roaming\python\python313\site-packages (from pandas) (2026.5)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (3.3.3)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: catboost in c:\users\49761366\appdata\roaming\python\python313\site-packages (1.2.10)
Requirement already satisfied: scikit-learn in c:\users\49761366\appdata\roaming\python\python313\site-packages (1.9.1)
Requirement already satisfied: pandas in c:\users\49761366\appdata\roaming\python\python313\site-packages (3.0.6)
Requirement already satisfied: graphviz in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (3.11.2)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (2.5.4)
Requirement already satisfied: scipy in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (1.18.1)
Requirement already satisfied: plotly in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (7.1.0)
Requirement already satisfied: six in c:\users\49761366\appdata\roaming\python\python313\site-packages (from catboost) (1.17.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\49761366\appdata\roaming\python\python313\site-packages (from pandas) (2026.5)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\49761366\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (3.3.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

data = pd.read_csv('housing.csv')
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [26]:
data = data.drop(columns=["longitude", "latitude"])
data.head()

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [27]:
data = pd.get_dummies(data, columns=["ocean_proximity"], dtype= int)
data.head()

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0,0,0,1,0
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0,0,0,1,0
2,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0,0,0,1,0
3,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0,0,0,1,0
4,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0,0,0,1,0

In [34]:

# Separar variables predictoras y objetivo
X = data.drop(columns=["median_house_value"])
y = data["median_house_value"]

In [35]:
# Dividir los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [41]:
# Crear el modelo
modelo = CatBoostRegressor(
    iterations=100,
    learning_rate=0.1,
    depth=4,
    verbose=0
)

# Entrenar el modelo
modelo.fit(X_train, y_train)

# Hacer predicciones
predicciones = modelo.predict(X_test)

# Evaluar el modelo
print(f"MAE: ${mean_absolute_error(y_test, predicciones):,.2f}")
print(f"RMSE:, ${root_mean_squared_error(y_test, predicciones):,.2f}")
print(f"R²:, {r2_score(y_test, predicciones)}")

MAE: $45,388.20
RMSE:, $64,554.38
R²:, 0.6819872514649025